# Standards: 0.11
---

# 1.5.1 - Ensure permissions on bootloader config are configured

- name: 1.5.1 - Ensure permissions on bootloader config are configured
  file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: '600'
  tags:
    - level-1
    - section-1
    - "1.5.1"
    - scored

